# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - vivx

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_ea604e0104ed466286b5b697af4d071d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6364873a4d124f3daef65add1dba3d43 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ea604e0104ed466286b5b697af4d071d }}/naomisoubhia/checkpoint2:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'vivx'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1e276cb77389495395f5acfc816e2357 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ea604e0104ed466286b5b697af4d071d }}/naomisoubhia/checkpoint2:${{ github.sha }}'